### ISSUE TITLE
Doesn't like ";"

### ISSUE THREAD

**Issue by borgauf** [usergenic/emacs.d#1]
If this is the version that I get from an elpa (marmalade) install then I need to tell you of a bug where this code (from SWI's Learn Prolog Now!)

```
woman(mia).
woman(jody).
woman(yolanda).
loves(vincent,mia).
loves(marsellus,mia).
loves(pumpkin,honey_bunny).
loves(honey_bunny,pumpkin).
```

when loaded doesn't like handling a variable list, i.e., when I ask

`?- woman(X).`

I get back the usual

`X = mia`

but then adding `;` and hitting return gives only one more, `X = jody` . . . and then it ends, giving back the prompt without giving the final `X = jolanda.` This behavior is with any variable listing greater than 2 members. Removing elpa (marmalade) 1.22 seems to solve the problem. Please advise.

**Comment by usergenic** [comment]
I think maybe this was intended for a different repo/audience, @borgauf ?

This repo is just my personal emacs.d folder.  I'm also not even actively using emacs these days (shame on me).

**Comment by borgauf** [comment]
Just curious, what are you using now?

**Comment by usergenic** [comment]
Was using vim but have been using Atom lately too.
